version: 2
jobs:
  build:
    docker:
      - image: gmao/geos-build-env-gcc-source:6.0.4
    working_directory: /root/project
    steps:
      - run:
          name: "GEOSchem_GridComp branch"
          command: echo ${CIRCLE_BRANCH}
      - checkout
      - run:
          name: "Checkout GEOSgcm fixture and update GEOSchem_GridComp branch"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}
            git clone git@github.com:GEOS-ESM/GEOSgcm.git
            cd GEOSgcm
            mepo init
            mepo clone
            mepo develop GEOSgcm_GridComp GEOSgcm_App GEOSchem_GridComp
            mepo checkout-if-exists ${CIRCLE_BRANCH}
            mepo status
      - run:
          name: "CMake"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/GEOSgcm
            mkdir build
            cd build
            cmake .. -DBASEDIR=$BASEDIR/Linux -DCMAKE_Fortran_COMPILER=gfortran -DCMAKE_BUILD_TYPE=Debug
      - run:
          name: "Build"
          command: |
            cd ${CIRCLE_WORKING_DIRECTORY}/GEOSgcm/build
            make -j2 install
