! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Stoichiometric Data Structures File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kpp_achem_gas_StoichiomSP.f90
! Time                 : Thu Jun 11 11:33:46 2015
! Working directory    : /gpfsm/dnb32/adarmeno/models/geos-5/heracles-UNSTABLE-DEV_MICROPHYSICS/src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphV
! Equation file        : kpp_achem_gas.kpp
! Output root filename : kpp_achem_gas
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE kpp_achem_gas_StoichiomSP

  USE kpp_achem_gas_Precision
  PUBLIC
  SAVE


! Row-compressed sparse data for the Jacobian of reaction products JVRP

  INTEGER, PARAMETER, DIMENSION(6) :: CROW_JVRP = (/ &
       1,  2,  3,  4,  5,  6 /)

  INTEGER, PARAMETER, DIMENSION(5) :: ICOL_JVRP = (/ &
       1,  1,  1,  2,  3 /)

  INTEGER, PARAMETER, DIMENSION(5) :: IROW_JVRP = (/ &
       1,  2,  3,  4,  5 /)



!  Stoichiometric Matrix in Compressed Column Sparse Format


  INTEGER, PARAMETER, DIMENSION(6) :: CCOL_STOICM = (/ &
       1,  3,  6,  8, 10, 11 /)

  INTEGER, PARAMETER, DIMENSION(10) :: IROW_STOICM = (/ &
       1,  2,  1,  2,  4,  1,  2,  2,  5,  3 /)

  INTEGER, PARAMETER, DIMENSION(10) :: ICOL_STOICM = (/ &
       1,  1,  2,  2,  2,  3,  3,  4,  4,  5 /)

  REAL(kind=dp), PARAMETER, DIMENSION(10) :: STOICM = (/ &
       -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  7.500000e-01_dp,  2.500000e-01_dp, &
       -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp,  1.000000e+00_dp,  -1.000000e+00_dp /)


END MODULE kpp_achem_gas_StoichiomSP

