! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : kpp_achem_gas_Monitor.f90
! Time                 : Thu Jun 11 11:33:46 2015
! Working directory    : /gpfsm/dnb32/adarmeno/models/geos-5/heracles-UNSTABLE-DEV_MICROPHYSICS/src/GEOSgcs_GridComp/GEOSgcm_GridComp/GEOSagcm_GridComp/GEOSphV
! Equation file        : kpp_achem_gas.kpp
! Output root filename : kpp_achem_gas
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE kpp_achem_gas_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(8) :: SPC_NAMES = (/ &
     'DMS            ','SO2            ','NH3            ', &
     'MSA            ','H2SO4          ','NO3            ', &
     'OH             ','H2O            ' /)

  INTEGER, PARAMETER, DIMENSION(8) :: LOOKAT = (/ &
       1,  2,  3,  4,  5,  6,  7,  8 /)

  INTEGER, PARAMETER, DIMENSION(7) :: MONITOR = (/ &
       1,  2,  3,  4,  5,  6,  7 /)

  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(5) :: EQN_NAMES = (/ &
     ' DMS + OH --> SO2                                                                                   ', &
     ' DMS + OH --> 0.75 SO2 + 0.25 MSA                                                                   ', &
     'DMS + NO3 --> SO2                                                                                   ', &
     ' SO2 + OH --> H2SO4                                                                                 ', &
     ' NH3 + OH --> H2O                                                                                   ' /)

! INLINED global variables

! End INLINED global variables


END MODULE kpp_achem_gas_Monitor
